
# Kubenewrepo

#    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Terraform'

on:
  push:
    paths-ignore:
    - "**.tfstate"
    - "**.tfstate.encrypted"
    branches: [ "main" ]
  pull_request:

env:
  AWS_REGION: us-east-1

  
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}


    

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: awssnuke
      run: |
        #aws iam create-account-alias --account-alias alia-aws-account
        wget https://github.com/rebuy-de/aws-nuke/releases/download/v2.16.0/aws-nuke-v2.16.0-linux-amd64.tar.gz
        tar -xvf aws-nuke-v2.16.0-linux-amd64.tar.gz
        mv aws-nuke-v2.16.0-linux-amd64 aws-nuke
        sudo mv aws-nuke /usr/local/bin/aws-nuke
        aws-nuke -h
        echo "alia-aws-account" | aws-nuke -c nuke-config.yml --profile default
    #aws-nuke -c nuke-config.yml --profile aws_nuke --no-dry-run

  
    
